"use client";

import React, { useRef, useState } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Share2, Download, Copy, Check, Twitter, Facebook } from "lucide-react";
import { format } from "date-fns";
import { toPng } from "html-to-image";
import { useToast } from "@/hooks/use-toast";

interface ShareSectionProps {
  birthDate?: Date;
  moonPhaseData: any;
}

export function ShareSection({ birthDate, moonPhaseData }: ShareSectionProps) {
  const { toast } = useToast();
  const cardRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  if (!birthDate || !moonPhaseData) return null;

  const formattedDate = format(birthDate, "MMMM d, yyyy");
  const shareUrl = typeof window !== "undefined" 
    ? `${window.location.origin}/result?date=${format(birthDate, "yyyy-MM-dd")}`
    : "";

  const shareText = `I was born during a ${moonPhaseData.phase} on ${formattedDate}. Discover your birth moon phase with LunarAura!`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    toast({
      title: "Link copied!",
      description: "Share link has been copied to clipboard",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    if (!cardRef.current) return;
    
    try {
      const dataUrl = await toPng(cardRef.current, { 
        quality: 0.95,
        backgroundColor: "#0f172a" 
      });
      
      const link = document.createElement("a");
      link.download = `lunar-aura-${format(birthDate, "yyyy-MM-dd")}.png`;
      link.href = dataUrl;
      link.click();
      
      toast({
        title: "Image downloaded!",
        description: "Your lunar card has been saved",
      });
    } catch (error) {
      console.error("Error generating image:", error);
      toast({
        title: "Download failed",
        description: "There was an error generating your image",
        variant: "destructive",
      });
    }
  };

  const handleShareTwitter = () => {
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
    window.open(twitterUrl, "_blank");
  };

  const handleShareFacebook = () => {
    const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`;
    window.open(facebookUrl, "_blank");
  };

  return (
    <div className="glass-morphism rounded-xl p-6 md:p-8 relative overflow-hidden">
      <div className="absolute inset-0 aurora-gradient opacity-20"></div>
      <div className="relative z-10">
        <h2 className="text-2xl font-serif font-bold mb-6">
          Share Your Lunar Card
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div 
            ref={cardRef} 
            className="glass-morphism rounded-xl p-6 aspect-[4/5] flex flex-col justify-between relative overflow-hidden"
          >
            <div className="absolute inset-0 aurora-gradient opacity-30"></div>
            <div className="relative z-10">
              <div className="text-center mb-6">
                <h3 className="text-lg font-serif font-bold text-primary">LunarAura</h3>
                <p className="text-sm text-muted-foreground">Birth Moon Reading</p>
              </div>

              <div className="flex flex-col items-center mb-6">
                <div className="w-24 h-24 rounded-full bg-background/40 flex items-center justify-center mb-4">
                  <span className="text-4xl">{moonPhaseData.zodiacSign.symbol}</span>
                </div>
                <h3 className="text-xl font-serif font-bold">{moonPhaseData.phase}</h3>
                <p className="text-muted-foreground text-sm">
                  {Math.round(moonPhaseData.illumination * 100)}% Illumination
                </p>
              </div>

              <div className="text-center space-y-2">
                <p className="text-sm">
                  <span className="text-muted-foreground">Sun Sign:</span>{" "}
                  <span className="font-medium">{moonPhaseData.zodiacSign.sign}</span>
                </p>
                <p className="text-sm">
                  <span className="text-muted-foreground">Moon Sign:</span>{" "}
                  <span className="font-medium">{moonPhaseData.moonSign.sign}</span>
                </p>
                <p className="text-sm">
                  <span className="text-muted-foreground">Birth Date:</span>{" "}
                  <span className="font-medium">{formattedDate}</span>
                </p>
              </div>
            </div>

            <div className="mt-4 text-center">
              <p className="text-xs text-muted-foreground">
                Generated by LunarAura | lunaraura.com
              </p>
            </div>
          </div>

          <div className="flex flex-col justify-center space-y-4">
            <div>
              <h3 className="text-lg font-medium mb-2">Share Your Lunar Profile</h3>
              <p className="text-sm text-muted-foreground mb-4">
                Download your personalized lunar card or share it with friends.
              </p>
            </div>

            <div className="space-y-3">
              <Button
                onClick={handleDownload}
                className="w-full bg-primary hover:bg-primary/90"
              >
                <Download className="mr-2 h-4 w-4" />
                Download Image
              </Button>
              
              <Button
                onClick={handleCopyLink}
                variant="outline"
                className="w-full"
              >
                {copied ? (
                  <>
                    <Check className="mr-2 h-4 w-4" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="mr-2 h-4 w-4" />
                    Copy Share Link
                  </>
                )}
              </Button>
              
              <div className="flex gap-3">
                <Button
                  onClick={handleShareTwitter}
                  variant="outline"
                  className="flex-1"
                >
                  <Twitter className="mr-2 h-4 w-4" />
                  Twitter
                </Button>
                <Button
                  onClick={handleShareFacebook}
                  variant="outline"
                  className="flex-1"
                >
                  <Facebook className="mr-2 h-4 w-4" />
                  Facebook
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}